# Generated by Django 6.0.3 on 2026-03-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('small_books', 'Small Books'), ('charts', 'Charts'), ('big_books', 'Big Books')], default='small_books', max_length=20),
        ),
    ]
