# Generated by Django 6.0.3 on 2026-03-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_email', models.EmailField(help_text='Store contact email address', max_length=254)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL', max_length=500)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL', max_length=500)),
                ('whatsapp_url', models.URLField(blank=True, help_text='WhatsApp contact URL', max_length=500)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
